// Generated by src/data/corpus-links.build.mjs — do not edit by hand.
//
// The start-here shelf on the homepage. Nine posts out of 322, in three
// groups a reader arriving cold can choose between by appetite.
//
// Chosen by measurement, not taste:
//   "Start a series" — the Part I of the longest multi-part series.
//   "The deep ones"  — the standalone posts with the most citations, which is
//                      the closest thing this corpus has to a rigor metric.
//   "One sitting"    — the shortest standalone posts that still clear six
//                      citations, so "short" never means "thin".
// Subject spread is enforced across the whole shelf: no two picks share a
// dominant subject term, so it cannot become nine essays about one thing.
// The counts behind each pick are in the comments below.

export interface FeaturedShelf {
  title: string;
  blurb: string;
  slugs: string[];
}

export const featuredShelves: FeaturedShelf[] = [
  {
    title: "Start a series",
    blurb: "Multi-part essays that build. Each one opens a thread the next part picks up.",
    slugs: [
      "the-manhattan-project", // 10 sources, ~3175 words, subject "einstein"
      "the-forgotten-front", // 7 sources, ~3211 words, subject "tannenberg"
      "the-congo-free-state", // 7 sources, ~2569 words, subject "congo"
    ],
  },
  {
    title: "The deep ones",
    blurb: "The most heavily sourced pieces in the archive, for readers who follow the footnotes.",
    slugs: [
      "the-hired-mourners", // 25 sources, ~5091 words, subject "ghana"
      "the-last-word", // 21 sources, ~4788 words, subject "kuuk"
      "the-colony-of-the-reasonable", // 21 sources, ~4594 words, subject "colony"
    ],
  },
  {
    title: "One sitting",
    blurb: "Shorter pieces that still carry their receipts. A good place to find out whether this is for you.",
    slugs: [
      "the-book-no-one-can-read", // 7 sources, ~1639 words, subject "voynich"
      "dead-letters", // 8 sources, ~2104 words, subject "kafka"
      "the-secret-life-of-soil", // 10 sources, ~2345 words, subject "bennett"
    ],
  },
];
