// Generated by src/data/corpus-links.build.mjs — do not edit by hand.
//
// Every multi-part series in the corpus, grouped from the "(Part N of M)"
// markers in the titles and ordered by Roman numeral rather than publish date.
// 10 series, 25 published parts.
//
// `total` is what the titles promise; `parts.length` is what exists. They
// differ while a series is still being written, and the reader is told so
// rather than being handed a link to a page that isn't there.
//
// Imported by ExplorationLayout, a server component: this table never reaches
// the browser, only the links rendered from it do.

export interface SeriesPart {
  slug: string;
  /** 1-based index parsed from the Roman numeral in the title. */
  part: number;
  /** The part's own subtitle: "The Purges", not the whole 60-character title. */
  partTitle: string;
  fullTitle: string;
}

export interface Series {
  /** The shared title before the colon: "The Manhattan Project". */
  name: string;
  /** Parts promised by the titles, which may exceed `parts.length`. */
  total: number;
  parts: SeriesPart[];
}

export const series: Series[] = [
  {
    name: "The Architecture of Terror",
    total: 3,
    parts: [
      { slug: "the-architecture-of-terror", part: 1, partTitle: "The Apparatus", fullTitle: "The Architecture of Terror: The Apparatus (Part I of III)" },
      { slug: "the-architecture-of-terror-part-2", part: 2, partTitle: "The Purges", fullTitle: "The Architecture of Terror: The Purges (Part II of III)" },
    ],
  },
  {
    name: "The Congo Free State",
    total: 3,
    parts: [
      { slug: "the-congo-free-state", part: 1, partTitle: "The King's Private Country", fullTitle: "The Congo Free State: The King's Private Country (Part I of III)" },
      { slug: "the-congo-free-state-part-2", part: 2, partTitle: "The Rubber Terror", fullTitle: "The Congo Free State: The Rubber Terror (Part II of III)" },
      { slug: "the-congo-free-state-part-3", part: 3, partTitle: "The First Human Rights Campaign", fullTitle: "The Congo Free State: The First Human Rights Campaign (Part III of III)" },
    ],
  },
  {
    name: "The Forgotten Front",
    total: 3,
    parts: [
      { slug: "the-forgotten-front", part: 1, partTitle: "The Tsar's Gamble", fullTitle: "The Forgotten Front: The Tsar's Gamble (Part I of III)" },
      { slug: "the-forgotten-front-part-2", part: 2, partTitle: "The Brusilov Offensive", fullTitle: "The Forgotten Front: The Brusilov Offensive (Part II of III)" },
      { slug: "the-forgotten-front-part-3", part: 3, partTitle: "Revolution and Collapse", fullTitle: "The Forgotten Front: Revolution and Collapse (Part III of III)" },
    ],
  },
  {
    name: "The Haitian Revolution",
    total: 2,
    parts: [
      { slug: "the-haitian-revolution", part: 1, partTitle: "The Fire", fullTitle: "The Haitian Revolution: The Fire (Part I of II)" },
      { slug: "the-haitian-revolution-part-2", part: 2, partTitle: "The Price of Freedom", fullTitle: "The Haitian Revolution: The Price of Freedom (Part II of II)" },
    ],
  },
  {
    name: "The Manhattan Project",
    total: 4,
    parts: [
      { slug: "the-manhattan-project", part: 1, partTitle: "The Physics of Desperation", fullTitle: "The Manhattan Project: The Physics of Desperation (Part I of IV)" },
      { slug: "the-manhattan-project-part-2", part: 2, partTitle: "The City on the Hill", fullTitle: "The Manhattan Project: The City on the Hill (Part II of IV)" },
      { slug: "the-manhattan-project-part-3", part: 3, partTitle: "The Decision", fullTitle: "The Manhattan Project: The Decision (Part III of IV)" },
      { slug: "the-manhattan-project-part-4", part: 4, partTitle: "The Inheritance", fullTitle: "The Manhattan Project: The Inheritance (Part IV of IV)" },
    ],
  },
  {
    name: "The Middle Passage",
    total: 2,
    parts: [
      { slug: "the-middle-passage", part: 1, partTitle: "The Crossing", fullTitle: "The Middle Passage: The Crossing (Part I of II)" },
      { slug: "the-middle-passage-part-2", part: 2, partTitle: "The Afterlife", fullTitle: "The Middle Passage: The Afterlife (Part II of II)" },
    ],
  },
  {
    name: "The Partition of India",
    total: 2,
    parts: [
      { slug: "the-partition-of-india", part: 1, partTitle: "The Radcliffe Line", fullTitle: "The Partition of India: The Radcliffe Line (Part I of II)" },
      { slug: "the-partition-of-india-part-2", part: 2, partTitle: "The Reckoning", fullTitle: "The Partition of India: The Reckoning (Part II of II)" },
    ],
  },
  {
    name: "The Scramble for Africa",
    total: 3,
    parts: [
      { slug: "the-scramble-for-africa", part: 1, partTitle: "Lines on a Map", fullTitle: "The Scramble for Africa: Lines on a Map (Part I of III)" },
      { slug: "the-scramble-for-africa-part-2", part: 2, partTitle: "The Violence of Conquest", fullTitle: "The Scramble for Africa: The Violence of Conquest (Part II of III)" },
      { slug: "the-scramble-for-africa-part-3", part: 3, partTitle: "The Long Shadow", fullTitle: "The Scramble for Africa: The Long Shadow (Part III of III)" },
    ],
  },
  {
    name: "The Siege of Leningrad",
    total: 2,
    parts: [
      { slug: "the-siege-of-leningrad", part: 1, partTitle: "The Ring Closes", fullTitle: "The Siege of Leningrad: The Ring Closes (Part I of II)" },
      { slug: "the-siege-of-leningrad-part-2", part: 2, partTitle: "Nine Hundred Days", fullTitle: "The Siege of Leningrad: Nine Hundred Days (Part II of II)" },
    ],
  },
  {
    name: "The World's Greatest Collision",
    total: 2,
    parts: [
      { slug: "the-worlds-greatest-collision", part: 1, partTitle: "The Meeting", fullTitle: "The World's Greatest Collision: The Meeting (Part I of II)" },
      { slug: "the-worlds-greatest-collision-part-2", part: 2, partTitle: "The Catastrophe", fullTitle: "The World's Greatest Collision: The Catastrophe (Part II of II)" },
    ],
  },
];

/** Index from slug to its series and position, built once at module load. */
const bySlug = new Map<string, { series: Series; index: number }>();
for (const group of series) {
  group.parts.forEach((part, index) => bySlug.set(part.slug, { series: group, index }));
}

export interface SeriesContext {
  series: Series;
  current: SeriesPart;
  previous: SeriesPart | null;
  next: SeriesPart | null;
}

/** The series a post belongs to, or null. Keyed by slug. */
export function seriesContextForSlug(slug: string): SeriesContext | null {
  const found = bySlug.get(slug);
  if (!found) return null;
  const { series: group, index } = found;
  return {
    series: group,
    current: group.parts[index],
    previous: index > 0 ? group.parts[index - 1] : null,
    next: index < group.parts.length - 1 ? group.parts[index + 1] : null,
  };
}
